services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-lzh}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-blockchain_db}
    ports:
      - "5433:5432"   # Host port 5433 → Container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-lzh} -d ${POSTGRES_DB:-blockchain_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://${POSTGRES_USER:-lzh}:${POSTGRES_PASSWORD:-123456}@db:5432/${POSTGRES_DB:-blockchain_db}}"
      REDIS_URL: redis://redis:6379
      DATA_DIR: ${DATA_DIR:-/app/data}
    volumes:
      - ./mvp_deploy_data:${DATA_DIR:-/app/data}
    env_file:
      - .env

volumes:
  pgdata:
  redisdata:
