[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]

ffi = true

# ✅ 只放在这里，不要在 [etherscan] 段再写一次
fs_permissions = [
  { access = "read",  path = "./" },
  { access = "write", path = "./docs/evidence" },
  { access = "write", path = "./broadcast" }
]

[fmt]
line_length = 100

[fuzz]
runs = 256

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# basesepolia = { key = "${BASESCAN_API_KEY}" }

[profile.verify_viair_off]
via_ir = false
optimizer = true
optimizer_runs = 200
evm_version = "paris"

[profile.verify_viair_on]
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "paris"
