[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

solc = "0.8.24"        
evm_version = "paris"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]

ffi = true
fs_permissions = [{ access = "read", path = "./" }]

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.9.4" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v5.0.2" }

[fmt]
line_length = 100

[fuzz]
runs = 256

[etherscan]
# sepolia     = { key = "${ETHERSCAN_API_KEY}" }
# basesepolia = { key = "${BASESCAN_API_KEY}" }
