[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

solc_version = "0.8.24"
evm_version  = "paris"
optimizer = true
optimizer_runs = 200

# 可选（有助于 IDE 解析）
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
