[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

solc_version = "0.8.24"
evm_version  = "paris"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]

# 需要用到外部命令/读取文件时启用
ffi = true
# 计划新增：限制文件系统权限（此处仅允许读取当前目录）
fs_permissions = [{ access = "read", path = "./"}]

# 格式化与模糊测试配置
[fmt]
line_length = 100

[fuzz]
runs = 256

# Day3 要用到的验证（先留空，环境变量里填 key 再解除注释）
[etherscan]
# sepolia     = { key = "${ETHERSCAN_API_KEY}" }
# basesepolia = { key = "${BASESCAN_API_KEY}" }
