name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 关键：所有 run 步骤在 evm/ 目录执行
defaults:
  run:
    working-directory: evm

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv

      - name: Gas report (artifact)
        if: always()
        run: |
          mkdir -p reports
          forge test --gas-report > reports/gas-ci.txt || true

      - name: Upload gas report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gas-ci
          # 注意：artifact 的 path 相对仓库根，因此要加 evm/
          path: evm/reports/gas-ci.txt
